-- ╔════════════════════════════════════════════════════════════╗
-- ║  BACKUP D1 PRODUCTION - DiagPV Hub                         ║
-- ║  Database: diagnostic-hub-production                       ║
-- ║  Date: $(date '+%Y-%m-%d %H:%M:%S')                              ║
-- ║  Total: 1929 enregistrements                               ║
-- ╚════════════════════════════════════════════════════════════╝

-- TABLE: shared_configurations (8 enregistrements)
    "results": [
      {
        "id": 1,
        "audit_id": 69,
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "string_count": 11,
        "modules_per_string": 22,
        "total_modules": 242,
        "advanced_config": "{\"mode\":\"simple\",\"stringCount\":11,\"modulesPerString\":22,\"totalModules\":242}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-10-27 09:43:12",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 2,
        "audit_id": 70,
        "audit_token": "76e6eb36-8b49-4255-99d3-55fc1adfc1c9",
        "string_count": 10,
        "modules_per_string": 22,
        "total_modules": 220,
        "advanced_config": "{\"mode\":\"simple\",\"stringCount\":10,\"modulesPerString\":22,\"totalModules\":220}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-10-27 09:43:12",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 3,
        "audit_id": 71,
        "audit_token": "da00e533-a50e-435e-bc71-18b62a15c7d3",
        "string_count": 1,
        "modules_per_string": 0,
        "total_modules": 0,
        "advanced_config": null,
        "is_advanced_mode": 0,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-10-27 12:57:14",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 4,
        "audit_id": 72,
        "audit_token": "5c69685d-fead-45b7-b6ee-2baac5bdb68f",
        "string_count": 2,
        "modules_per_string": 10,
        "total_modules": 20,
        "advanced_config": "{\"mode\":\"simple\",\"stringCount\":2,\"modulesPerString\":10,\"totalModules\":20}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-10-28 14:41:25",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 5,
        "audit_id": 1,
        "audit_token": "a9969adf-2309-4ec1-b087-325900036554",
        "string_count": 0,
        "modules_per_string": 0,
        "total_modules": 0,
        "advanced_config": "{\"panneaux_par_string\":24,\"nb_strings_total\":12,\"puissance_crete_wc\":8640,\"technologie\":\"Monocristallin PERC\",\"fabricant\":\"Sunpower\",\"reference\":\"SPR-X21-360\"}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-11-18 10:52:51",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 6,
        "audit_id": 2,
        "audit_token": "c89d4e71-ec84-4a48-b87d-6368853092c5",
        "string_count": 5,
        "modules_per_string": 20,
        "total_modules": 100,
        "advanced_config": "{\"mode\":\"simple\",\"stringCount\":5,\"modulesPerString\":20}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-11-19 09:24:43",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 7,
        "audit_id": 73,
        "audit_token": "0e74eb29-69d7-4923-8675-32dbb8e926d1",
        "string_count": 10,
        "modules_per_string": 0,
        "total_modules": 242,
        "advanced_config": "{\"mode\":\"advanced\",\"totalModules\":242,\"stringCount\":10,\"strings\":[{\"mpptNumber\":1,\"moduleCount\":26,\"physicalRow\":1,\"physicalCol\":0},{\"mpptNumber\":2,\"moduleCount\":24,\"physicalRow\":2,\"physicalCol\":0},{\"mpptNumber\":3,\"moduleCount\":24,\"physicalRow\":3,\"physicalCol\":0},{\"mpptNumber\":4,\"moduleCount\":24,\"physicalRow\":4,\"physicalCol\":0},{\"mpptNumber\":5,\"moduleCount\":24,\"physicalRow\":5,\"physicalCol\":0},{\"mpptNumber\":6,\"moduleCount\":24,\"physicalRow\":6,\"physicalCol\":0},{\"mpptNumber\":7,\"moduleCount\":24,\"physicalRow\":7,\"physicalCol\":0},{\"mpptNumber\":8,\"moduleCount\":24,\"physicalRow\":8,\"physicalCol\":0},{\"mpptNumber\":9,\"moduleCount\":24,\"physicalRow\":9,\"physicalCol\":0},{\"mpptNumber\":10,\"moduleCount\":24,\"physicalRow\":10,\"physicalCol\":0}]}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-11-21 10:31:43",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      },
      {
        "id": 8,
        "audit_id": 68,
        "audit_token": "c6343d13-2311-4a8f-909a-adf02e52d9ad",
        "string_count": 5,
        "modules_per_string": 20,
        "total_modules": 100,
        "advanced_config": "{\"mode\":\"simple\",\"stringCount\":5,\"modulesPerString\":20,\"totalModules\":100}",
        "is_advanced_mode": 1,
        "module_model": null,
        "module_power_wp": null,
        "total_power_kwc": null,
        "inverter_model": null,
        "inverter_count": 1,
        "installation_type": null,
        "orientation": null,
        "tilt_angle": null,
        "validation_status": "validated",
        "validated_by": null,
        "validated_at": null,
        "created_at": "2025-11-21 16:28:33",
        "updated_at": "2025-12-03 15:16:26",
        "created_by": "migration_0052"
      }
    ],
    "success": true,
    "meta": {
      "served_by": "v3-prod",
      "served_by_region": "WNAM",
      "served_by_primary": true,
      "timings": {
        "sql_duration_ms": 0.5223
      },
      "duration": 0.5223,
      "changes": 0,
      "last_row_id": 0,
      "changed_db": false,
      "size_after": 3944448,
      "rows_read": 8,
      "rows_written": 0,
      "total_attempts": 1
    }
  }
]

-- TABLE: iv_measurements (484 enregistrements)
    "results": [
      {
        "id": 1,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 1,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:25",
        "module_identifier": "S1-1",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 2,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 1,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:25",
        "module_identifier": "S1-1",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 3,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 2,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:25",
        "module_identifier": "S1-2",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 4,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 2,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-2",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 5,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 3,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-3",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 6,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 3,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-3",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 7,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 4,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-4",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 8,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 4,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-4",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 9,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 5,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-5",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 10,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 5,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-5",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 11,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 6,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-6",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 12,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 6,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-6",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 13,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 7,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-7",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 14,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 7,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-7",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 15,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 8,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-8",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 16,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 8,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-8",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 17,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 9,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-9",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 18,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 9,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-9",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 19,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 10,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-10",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 20,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 10,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:26",
        "module_identifier": "S1-10",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 21,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 11,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-11",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 22,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 11,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-11",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 23,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 12,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-12",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 24,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 12,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-12",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 25,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 13,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-13",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 26,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 13,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-13",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 27,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 14,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-14",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 28,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 14,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-14",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 29,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 15,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-15",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 30,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 15,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-15",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 31,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 16,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-16",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 32,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 16,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-16",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 33,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 17,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-17",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 34,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 17,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-17",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 35,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 18,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-18",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 36,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 18,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-18",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 37,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 19,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:27",
        "module_identifier": "S1-19",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 38,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 19,
        "measurement_type": "dark",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,
        "irradiance": null,
        "temperature_module": null,
        "temperature_ambient": null,
        "iv_curve_data": null,
        "pmax_stc_corrected": null,
        "deviation_from_datasheet": null,
        "rs": null,
        "rsh": null,
        "notes": null,
        "created_at": "2025-12-04 09:04:28",
        "module_identifier": "S1-19",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": null
      },
      {
        "id": 39,
        "intervention_id": null,
        "string_number": 1,
        "module_number": 20,
        "measurement_type": "reference",
        "isc": null,
        "voc": null,
        "pmax": null,
        "impp": null,
        "vmpp": null,
        "fill_factor": null,

-- TABLE: visual_inspections (40 enregistrements)
    "results": [
      {
        "id": 1,
        "intervention_id": null,
        "audit_token": "c89d4e71-ec84-4a48-b87d-6368853092c5",
        "audit_id": null,
        "inspection_type": "structural",
        "string_number": 1,
        "module_number": 5,
        "location_description": null,
        "defect_found": 1,
        "defect_type": "delamination",
        "severity_level": 2,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "Délamination visible sur module S1-5",
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 09:34:10",
        "plant_id": null,
        "conformite": null,
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "general",
        "checklist_section": null,
        "item_order": 0,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 2,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763575057744",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Méthode démontage conforme notice",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 17:57:43",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "1. Démontage Panneaux (Min 25)",
        "item_order": 2,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 3,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763575412852",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Méthode démontage conforme notice",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:03:42",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "1. Démontage Panneaux (Min 25)",
        "item_order": 2,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 4,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763575412852",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Fixation SI conforme DTU 40.35",
        "defect_found": 1,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:03:43",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "2. Montage & Serrage Structure Intégration (SI)",
        "item_order": 100,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 5,
        "intervention_id": 5,
        "audit_token": "GIRASOLE-TOITURE-3-1763575472083",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Méthode démontage conforme notice",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:04:47",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "1. Démontage Panneaux (Min 25)",
        "item_order": 2,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 6,
        "intervention_id": 5,
        "audit_token": "GIRASOLE-TOITURE-3-1763575472083",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Fixation SI conforme DTU 40.35",
        "defect_found": 1,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:04:48",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "2. Montage & Serrage Structure Intégration (SI)",
        "item_order": 100,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 7,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763576201914",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Serrage final conforme",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:17:34",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "7. Remontage & Vérifications Finales",
        "item_order": 601,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 8,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763576201914",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Propreté zone intervention",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": "[5]",
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:17:35",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "7. Remontage & Vérifications Finales",
        "item_order": 602,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 9,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763577607243",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Méthode démontage conforme notice",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:40:29",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "1. Démontage Panneaux (Min 25)",
        "item_order": 2,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 10,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763577607243",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Couple serrage respecté",
        "defect_found": 1,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:40:30",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "2. Montage & Serrage Structure Intégration (SI)",
        "item_order": 101,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 11,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763577607243",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Serrage panneaux correct",
        "defect_found": 1,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:40:30",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "3. Montage & Serrage Panneaux",
        "item_order": 201,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 12,
        "intervention_id": 4,
        "audit_token": "GIRASOLE-TOITURE-2-1763577607243",
        "audit_id": null,
        "inspection_type": "toiture_dtu4035",
        "string_number": null,
        "module_number": null,
        "location_description": "Fixations câbles conformes",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": "[7]",
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": null,
        "inspection_date": "2025-11-19",
        "created_at": "2025-11-19 18:40:31",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "toiture_dtu4035",
        "checklist_section": "4. Fixations Cheminements DC",
        "item_order": 300,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 13,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-01",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Protection différentielle 30mA présente et fonctionnelle\", \"normReference\": \"NF C 15-100 Section 531.2\", \"code\": \"PROT-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "PROTECTIONS",
        "checklist_section": "Protection différentielle",
        "item_order": 0,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 14,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-02",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Disjoncteur DC adapté à la puissance\", \"normReference\": \"NF C 15-100 Section 536\", \"code\": \"PROT-02\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "PROTECTIONS",
        "checklist_section": "Disjoncteur DC",
        "item_order": 1,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 15,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-03",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Continuité liaison équipotentielle < 0.5 Ω\", \"normReference\": \"NF C 15-100 Section 543.1\", \"code\": \"TERRE-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "MISE_A_TERRE",
        "checklist_section": "Continuité terre",
        "item_order": 2,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 16,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-04",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Résistance de terre < 100 Ω\", \"normReference\": \"NF C 15-100 Section 542\", \"code\": \"TERRE-02\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "MISE_A_TERRE",
        "checklist_section": "Résistance terre",
        "item_order": 3,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 17,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-05",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Section câbles DC conformes (6mm² min)\", \"normReference\": \"NF C 15-100 Section 523\", \"code\": \"CABL-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "CABLAGE",
        "checklist_section": "Section câbles",
        "item_order": 4,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 18,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "CONF-06",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Étiquetage câbles DC/AC conforme\", \"normReference\": \"UTE C 15-712-1\", \"code\": \"CABL-02\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "sans_objet",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "CABLAGE",
        "checklist_section": "Étiquetage",
        "item_order": 5,
        "checklist_type": "CONFORMITE",
        "project_id": 5
      },
      {
        "id": 19,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "TOIT-01",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"État membrane étanchéité - pas de déchirures\", \"normReference\": \"DTU 40.35 Article 5.2\", \"code\": \"ETAN-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "ETANCHEITE",
        "checklist_section": "Membrane",
        "item_order": 0,
        "checklist_type": "TOITURE",
        "project_id": 5
      },
      {
        "id": 20,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "TOIT-02",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Traversées étanches (passe-câbles)\", \"normReference\": \"DTU 40.35 Article 7.3\", \"code\": \"ETAN-02\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "ETANCHEITE",
        "checklist_section": "Traversées",
        "item_order": 1,
        "checklist_type": "TOITURE",
        "project_id": 5
      },
      {
        "id": 21,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "TOIT-03",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Système fixation adapté au support\", \"normReference\": \"DTU 40.35 Article 6.1\", \"code\": \"FIX-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "FIXATIONS",
        "checklist_section": "Système fixation",
        "item_order": 2,
        "checklist_type": "TOITURE",
        "project_id": 5
      },
      {
        "id": 22,
        "intervention_id": null,
        "audit_token": "GIRASOLE-89219-20251120",
        "audit_id": null,
        "inspection_type": "TOIT-04",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Rails aluminium sans corrosion\", \"normReference\": \"DTU 40.35 Article 6.2\", \"code\": \"STRUC-01\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:29:40",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "STRUCTURE",
        "checklist_section": "Rails",
        "item_order": 3,
        "checklist_type": "TOITURE",
        "project_id": 5
      },
      {
        "id": 23,
        "intervention_id": 1,
        "audit_token": "GIRASOLE-CONFORMITE-59-TEST",
        "audit_id": null,
        "inspection_type": "CONF-01",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Protection différentielle 30mA\", \"normReference\": \"NF C 15-100 Section 531.2\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "PROTECTIONS",
        "checklist_section": "Protection différentielle",
        "item_order": 0,
        "checklist_type": "CONFORMITE",
        "project_id": 59
      },
      {
        "id": 24,
        "intervention_id": 1,
        "audit_token": "GIRASOLE-CONFORMITE-59-TEST",
        "audit_id": null,
        "inspection_type": "CONF-02",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Disjoncteur magnétothermique DC\", \"normReference\": \"NF C 15-100\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "PROTECTIONS",
        "checklist_section": "Disjoncteur DC",
        "item_order": 1,
        "checklist_type": "CONFORMITE",
        "project_id": 59
      },
      {
        "id": 25,
        "intervention_id": 1,
        "audit_token": "GIRASOLE-CONFORMITE-59-TEST",
        "audit_id": null,
        "inspection_type": "CONF-03",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Continuité mise à la terre\", \"normReference\": \"NF C 15-100 Section 542.2\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "MISE_A_TERRE",
        "checklist_section": "Continuité terre",
        "item_order": 2,
        "checklist_type": "CONFORMITE",
        "project_id": 59
      },
      {
        "id": 26,
        "intervention_id": 1,
        "audit_token": "GIRASOLE-CONFORMITE-59-TEST",
        "audit_id": null,
        "inspection_type": "CONF-04",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Câbles conformes UV\", \"normReference\": \"NF C 15-100\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "sans_objet",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "CABLAGE",
        "checklist_section": "Câbles DC",
        "item_order": 3,
        "checklist_type": "CONFORMITE",
        "project_id": 59
      },
      {
        "id": 27,
        "intervention_id": 1,
        "audit_token": "GIRASOLE-CONFORMITE-59-TEST",
        "audit_id": null,
        "inspection_type": "CONF-05",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Serrage connecteurs MC4\", \"normReference\": \"NF C 15-100\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "CABLAGE",
        "checklist_section": "Connecteurs",
        "item_order": 4,
        "checklist_type": "CONFORMITE",
        "project_id": 59
      },
      {
        "id": 28,
        "intervention_id": 2,
        "audit_token": "GIRASOLE-TOITURE-60-TEST",
        "audit_id": null,
        "inspection_type": "TOIT-01",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"État membrane étanchéité\", \"normReference\": \"DTU 40.35\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "ETANCHEITE",
        "checklist_section": "Membrane",
        "item_order": 0,
        "checklist_type": "TOITURE",
        "project_id": 60
      },
      {
        "id": 29,
        "intervention_id": 2,
        "audit_token": "GIRASOLE-TOITURE-60-TEST",
        "audit_id": null,
        "inspection_type": "TOIT-02",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Traversées toiture\", \"normReference\": \"DTU 40.35\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "ETANCHEITE",
        "checklist_section": "Traversées",
        "item_order": 1,
        "checklist_type": "TOITURE",
        "project_id": 60
      },
      {
        "id": 30,
        "intervention_id": 2,
        "audit_token": "GIRASOLE-TOITURE-60-TEST",
        "audit_id": null,
        "inspection_type": "TOIT-05",
        "string_number": null,
        "module_number": null,
        "location_description": null,
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "{\"description\": \"Système fixation panneaux\", \"normReference\": \"DTU 40.35\"}",
        "inspection_date": "2025-11-20",
        "created_at": "2025-11-20 10:30:17",
        "plant_id": null,
        "conformite": "non_conforme",
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "FIXATIONS",
        "checklist_section": "Fixations",
        "item_order": 2,
        "checklist_type": "TOITURE",
        "project_id": 60
      },
      {
        "id": 31,
        "intervention_id": null,
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69,
        "inspection_type": "structural",
        "string_number": null,
        "module_number": null,
        "location_description": "Ensemble installation",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "Contrôle fixations modules, état rails, vis de serrage, structures porteuses",
        "inspection_date": "2025-12-04",
        "created_at": "2025-12-04 09:27:37",
        "plant_id": null,
        "conformite": null,
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "mechanical",
        "checklist_section": "Structure & Fixations",
        "item_order": 1,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 32,
        "intervention_id": null,
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69,
        "inspection_type": "electrical",
        "string_number": null,
        "module_number": null,
        "location_description": "Boîtes jonction, MC4, chemins câbles",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "Vérifier étanchéité MC4, serrage connexions, état câbles DC/AC, boîtes jonction",
        "inspection_date": "2025-12-04",
        "created_at": "2025-12-04 09:27:37",
        "plant_id": null,
        "conformite": null,
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "electrical",
        "checklist_section": "Câblage & Connexions",
        "item_order": 2,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 33,
        "intervention_id": null,
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69,
        "inspection_type": "mechanical",
        "string_number": null,
        "module_number": null,
        "location_description": "Modules photovoltaïques",
        "defect_found": 0,
        "defect_type": null,
        "severity_level": null,
        "photo_url": null,
        "gps_latitude": null,
        "gps_longitude": null,
        "corrective_action_required": 0,
        "corrective_action_description": null,
        "notes": "Contrôle verre (fissures, impacts), cadre (déformation, corrosion), joint (décollement)",
        "inspection_date": "2025-12-04",
        "created_at": "2025-12-04 09:27:37",
        "plant_id": null,
        "conformite": null,
        "prescriptions_girasole": null,
        "bonnes_pratiques": null,
        "audit_category": "mechanical",
        "checklist_section": "État Modules PV",
        "item_order": 3,
        "checklist_type": "IEC_62446",
        "project_id": null
      },
      {
        "id": 34,
        "intervention_id": null,
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69,
        "inspection_type": "safety",
        "string_number": null,
        "module_number": null,
        "location_description": "Onduleurs, protections, signalétique",
        "defect_found": 0,

-- TABLE: isolation_tests (3 enregistrements)
    "results": [
      {
        "id": 1,
        "test_token": "test_1764840625824_um1ynb",
        "plant_id": null,
        "zone_id": null,
        "audit_el_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "test_date": "2025-12-04",
        "test_type": "DC",
        "operator_name": null,
        "equipment_used": "Multimètre isolement 1000V DC",
        "dc_positive_to_earth": null,
        "dc_negative_to_earth": null,
        "dc_positive_to_negative": null,
        "ac_to_earth": null,
        "temperature_celsius": null,
        "humidity_percent": null,
        "weather_conditions": null,
        "is_conform": 0,
        "threshold_mohm": 1,
        "notes": "Test isolement DC+ vers terre selon IEC 62446-1 (≥ 1 MΩ)",
        "non_conformity_details": null,
        "corrective_actions": null,
        "imported_from_file": null,
        "raw_data_json": null,
        "created_at": "2025-12-04 09:30:25",
        "updated_at": "2025-12-04 09:30:25",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69
      },
      {
        "id": 2,
        "test_token": "test_1764840626065_byr2k",
        "plant_id": null,
        "zone_id": null,
        "audit_el_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "test_date": "2025-12-04",
        "test_type": "DC",
        "operator_name": null,
        "equipment_used": "Multimètre isolement 1000V DC",
        "dc_positive_to_earth": null,
        "dc_negative_to_earth": null,
        "dc_positive_to_negative": null,
        "ac_to_earth": null,
        "temperature_celsius": null,
        "humidity_percent": null,
        "weather_conditions": null,
        "is_conform": 0,
        "threshold_mohm": 1,
        "notes": "Test isolement DC- vers terre selon IEC 62446-1 (≥ 1 MΩ)",
        "non_conformity_details": null,
        "corrective_actions": null,
        "imported_from_file": null,
        "raw_data_json": null,
        "created_at": "2025-12-04 09:30:26",
        "updated_at": "2025-12-04 09:30:26",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69
      },
      {
        "id": 3,
        "test_token": "test_1764840626135_bktda",
        "plant_id": null,
        "zone_id": null,
        "audit_el_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "test_date": "2025-12-04",
        "test_type": "AC",
        "operator_name": null,
        "equipment_used": "Multimètre isolement 500V AC",
        "dc_positive_to_earth": null,
        "dc_negative_to_earth": null,
        "dc_positive_to_negative": null,
        "ac_to_earth": null,
        "temperature_celsius": null,
        "humidity_percent": null,
        "weather_conditions": null,
        "is_conform": 0,
        "threshold_mohm": 0.5,
        "notes": "Test isolement sortie onduleur selon NF C 15-100 (≥ 0.5 MΩ)",
        "non_conformity_details": null,
        "corrective_actions": null,
        "imported_from_file": null,
        "raw_data_json": null,
        "created_at": "2025-12-04 09:30:26",
        "updated_at": "2025-12-04 09:30:26",
        "audit_token": "a4e19950-c73c-412c-be4d-699c9de1dde1",
        "audit_id": 69
      }
    ],
    "success": true,
    "meta": {
      "served_by": "v3-prod",
      "served_by_region": "WNAM",
      "served_by_primary": true,
      "timings": {
        "sql_duration_ms": 0.477
      },
      "duration": 0.477,
      "changes": 0,
      "last_row_id": 0,
      "changed_db": false,
      "size_after": 3944448,
      "rows_read": 3,
      "rows_written": 0,
      "total_attempts": 1
    }
  }
]

