-- Populate all 10 zones with modules (Strings 2-10: 24 modules each)
-- This creates the missing 216 modules for zones 15-23

-- String 2 (Zone 15) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 15, 'S2-P' || CAST(n AS TEXT), 2, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 3 (Zone 16) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 16, 'S3-P' || CAST(n AS TEXT), 3, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 4 (Zone 17) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 17, 'S4-P' || CAST(n AS TEXT), 4, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 5 (Zone 18) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 18, 'S5-P' || CAST(n AS TEXT), 5, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 6 (Zone 19) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 19, 'S6-P' || CAST(n AS TEXT), 6, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 7 (Zone 20) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 20, 'S7-P' || CAST(n AS TEXT), 7, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 8 (Zone 21) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 21, 'S8-P' || CAST(n AS TEXT), 8, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 9 (Zone 22) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 22, 'S9-P' || CAST(n AS TEXT), 9, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);

-- String 10 (Zone 23) - 24 modules
INSERT INTO pv_modules (zone_id, module_identifier, string_number, position_in_string, pos_x_meters, pos_y_meters, module_status, el_defect_type) 
SELECT 23, 'S10-P' || CAST(n AS TEXT), 10, n, 0, 0, 'pending', 'none'
FROM (SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24);
