
 ⛅️ wrangler 4.41.0 (update available 4.52.1)
─────────────────────────────────────────────
🌀 Executing on remote database diagnostic-hub-production (72be68d4-c5c5-4854-9ead-3bbcc131d199):
🌀 To execute on your local development database, remove the --remote flag from your wrangler command.
🚣 Executed 1 command in 0.4221ms
[
  {
    "results": [
      {
        "sql": "CREATE TABLE _cf_KV (\n        key TEXT PRIMARY KEY,\n        value BLOB\n      ) WITHOUT ROWID"
      },
      {
        "sql": "CREATE TABLE active_technicians (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    audit_token TEXT NOT NULL,                  \n    technician_id TEXT NOT NULL,                \n    technician_name TEXT DEFAULT 'Technicien',  \n    last_seen DATETIME DEFAULT CURRENT_TIMESTAMP,  \n    \n    \n    UNIQUE(audit_token, technician_id)          \n)"
      },
      {
        "sql": "CREATE TABLE activity_logs (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER,\n  action TEXT NOT NULL,  \n  resource_type TEXT,    \n  resource_id TEXT,\n  details TEXT,          \n  ip_address TEXT,\n  user_agent TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE audit_assignments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  audit_token TEXT NOT NULL,\n  user_id INTEGER NOT NULL,\n  can_view BOOLEAN DEFAULT 1,\n  can_edit BOOLEAN DEFAULT 0,\n  can_delete BOOLEAN DEFAULT 0,\n  allowed_modules TEXT,  \n  assigned_by INTEGER NOT NULL,\n  assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  status TEXT DEFAULT 'active' CHECK(status IN ('active', 'revoked', 'expired')),\n  expires_at DATETIME,\n  notes TEXT,\n  \n  FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE CASCADE,\n  FOREIGN KEY (assigned_by) REFERENCES auth_users(id),\n  UNIQUE(audit_token, user_id)\n)"
      },
      {
        "sql": "CREATE TABLE audit_modules (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    audit_token TEXT NOT NULL,                  \n    module_id TEXT NOT NULL,                    \n    status TEXT NOT NULL,                       \n    comment TEXT,                               \n    technician_id TEXT NOT NULL,                \n    technician_name TEXT DEFAULT 'Technicien',  \n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,  \n    \n    \n    UNIQUE(audit_token, module_id)              \n)"
      },
      {
        "sql": "CREATE TABLE \"audit_modules_complete\" (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    audit_token TEXT NOT NULL,\n    module_id TEXT NOT NULL,\n    \n    \n    string_number INTEGER,\n    module_position INTEGER,\n    \n    \n    status TEXT NOT NULL,\n    comment TEXT,\n    defects TEXT, \n    \n    \n    voltage_v REAL,\n    current_a REAL,\n    temperature_c REAL,\n    \n    \n    technician_id TEXT NOT NULL,\n    technician_name TEXT DEFAULT 'Technicien',\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    \n    UNIQUE(audit_token, module_id),\n    FOREIGN KEY(audit_token) REFERENCES audits(audit_token) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE \"audit_reports\" (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    audit_token TEXT NOT NULL,\n    \n    report_type TEXT NOT NULL, \n    report_title TEXT NOT NULL,\n    \n    generated_by TEXT NOT NULL,\n    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    \n    FOREIGN KEY(audit_token) REFERENCES audits(audit_token) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE audits (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  audit_token TEXT UNIQUE NOT NULL,\n  \n  \n  intervention_id INTEGER,\n  client_id INTEGER,\n  project_id INTEGER,\n  \n  \n  project_name TEXT NOT NULL,\n  client_name TEXT NOT NULL,\n  location TEXT,\n  audit_date DATE DEFAULT CURRENT_DATE,\n  \n  \n  modules_enabled TEXT NOT NULL DEFAULT '[\"EL\"]',\n  \n  \n  configuration_json TEXT,\n  \n  \n  status TEXT DEFAULT 'en_cours',\n  \n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  completed_at DATETIME, pv_zone_id INTEGER, pv_plant_id INTEGER,\n  \n  \n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE SET NULL,\n  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE SET NULL,\n  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE auth_users (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  email TEXT UNIQUE NOT NULL,\n  password_hash TEXT NOT NULL,\n  full_name TEXT NOT NULL,\n  company TEXT,\n  role TEXT NOT NULL CHECK(role IN ('admin', 'subcontractor', 'client', 'auditor')),\n  is_active BOOLEAN DEFAULT 1,\n  must_change_password BOOLEAN DEFAULT 0,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  last_login_at DATETIME\n)"
      },
      {
        "sql": "CREATE TABLE calepinage_cables (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id TEXT NOT NULL,\n  from_module TEXT NOT NULL,  \n  to_module TEXT NOT NULL,    \n  cable_points TEXT,          \n  cable_color TEXT DEFAULT '#dc2626',  \n  arrow_type TEXT DEFAULT 'end',       \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (project_id) REFERENCES calepinage_layouts(project_id)\n)"
      },
      {
        "sql": "CREATE TABLE calepinage_layouts (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id TEXT UNIQUE NOT NULL,  \n  layout_name TEXT NOT NULL,\n  layout_data TEXT NOT NULL,  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n, module_type TEXT DEFAULT 'el', view_box_json TEXT NOT NULL DEFAULT '{\"width\":2400,\"height\":1200,\"gridSize\":20}', modules_json TEXT NOT NULL DEFAULT '[]', arrows_json TEXT DEFAULT '[]', zones_json TEXT DEFAULT '[]')"
      },
      {
        "sql": "CREATE TABLE calepinage_zones (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id TEXT NOT NULL,\n  zone_name TEXT,\n  string_numbers TEXT NOT NULL,  \n  border_color TEXT DEFAULT '#dc2626',\n  border_width INTEGER DEFAULT 3,\n  background_color TEXT DEFAULT 'transparent',\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (project_id) REFERENCES calepinage_layouts(project_id)\n)"
      },
      {
        "sql": "CREATE TABLE criteres_labellisation (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  code TEXT UNIQUE NOT NULL, \n  nom TEXT NOT NULL,\n  description TEXT,\n  categorie TEXT NOT NULL, \n  obligatoire BOOLEAN DEFAULT 1,\n  points INTEGER DEFAULT 0, \n  actif BOOLEAN DEFAULT 1,\n  ordre INTEGER DEFAULT 0,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE crm_clients (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  company_name TEXT NOT NULL,\n  client_type TEXT NOT NULL DEFAULT 'professional',  \n  siret TEXT,\n  tva_number TEXT,\n  \n  \n  address TEXT,\n  postal_code TEXT,\n  city TEXT,\n  country TEXT DEFAULT 'France',\n  \n  \n  main_contact_name TEXT,\n  main_contact_email TEXT,\n  main_contact_phone TEXT,\n  \n  \n  status TEXT DEFAULT 'active',                      \n  acquisition_source TEXT,\n  assigned_to INTEGER,                               \n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (assigned_to) REFERENCES auth_users(id)\n)"
      },
      {
        "sql": "CREATE TABLE crm_contacts (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  client_id INTEGER NOT NULL,\n  \n  \n  first_name TEXT NOT NULL,\n  last_name TEXT NOT NULL,\n  role TEXT,\n  department TEXT,\n  \n  \n  email TEXT,\n  phone TEXT,\n  mobile TEXT,\n  \n  \n  is_primary BOOLEAN DEFAULT 0,\n  receive_reports BOOLEAN DEFAULT 1,\n  receive_invoices BOOLEAN DEFAULT 0,\n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE d1_migrations(\n\t\tid         INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\tname       TEXT UNIQUE,\n\t\tapplied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL\n)"
      },
      {
        "sql": "CREATE TABLE designer_layouts (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  modules_count INTEGER NOT NULL,\n  modules_data TEXT NOT NULL,      \n  module_specs TEXT NOT NULL,      \n  map_center TEXT NOT NULL,        \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n, zone_id INTEGER, zoom_level INTEGER DEFAULT 18)"
      },
      {
        "sql": "CREATE TABLE diagnostiqueurs (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  nom TEXT NOT NULL,\n  prenom TEXT NOT NULL,\n  email TEXT UNIQUE NOT NULL,\n  telephone TEXT,\n  \n  \n  entreprise TEXT,\n  siret TEXT,\n  adresse TEXT,\n  code_postal TEXT,\n  ville TEXT,\n  \n  \n  statut_label TEXT NOT NULL DEFAULT 'candidat' CHECK(statut_label IN ('candidat', 'en_evaluation', 'labellise', 'suspendu', 'refuse')),\n  date_candidature DATETIME DEFAULT CURRENT_TIMESTAMP,\n  date_labellisation DATETIME,\n  date_expiration_label DATETIME,\n  numero_label TEXT UNIQUE, \n  \n  \n  certifications TEXT, \n  formations TEXT, \n  cv_url TEXT,\n  kbis_url TEXT,\n  assurance_rc_url TEXT,\n  \n  \n  annees_experience INTEGER DEFAULT 0,\n  nombre_audits_realises INTEGER DEFAULT 0,\n  specialites TEXT, \n  \n  \n  note_moyenne REAL DEFAULT 0, \n  taux_conformite_moyen REAL DEFAULT 0, \n  delai_moyen_rapport INTEGER DEFAULT 0, \n  \n  \n  zones_intervention TEXT, \n  disponible BOOLEAN DEFAULT 1,\n  capacite_audits_mois INTEGER DEFAULT 0,\n  \n  \n  notes_internes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  created_by INTEGER, \n  \n  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE diagnostiqueurs_audits (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  diagnostiqueur_id INTEGER NOT NULL,\n  audit_token TEXT NOT NULL,\n  \n  \n  date_assignation DATETIME DEFAULT CURRENT_TIMESTAMP,\n  date_realisation DATETIME,\n  date_rapport_envoye DATETIME,\n  delai_rapport_jours INTEGER, \n  \n  \n  note_client INTEGER, \n  commentaire_client TEXT,\n  note_diagpv INTEGER, \n  commentaire_diagpv TEXT,\n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (diagnostiqueur_id) REFERENCES diagnostiqueurs(id) ON DELETE CASCADE,\n  FOREIGN KEY (audit_token) REFERENCES audits(audit_token) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE diagnostiqueurs_criteres (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  diagnostiqueur_id INTEGER NOT NULL,\n  critere_id INTEGER NOT NULL,\n  \n  valide BOOLEAN DEFAULT 0,\n  date_validation DATETIME,\n  valide_par INTEGER, \n  commentaire TEXT,\n  document_url TEXT, \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (diagnostiqueur_id) REFERENCES diagnostiqueurs(id) ON DELETE CASCADE,\n  FOREIGN KEY (critere_id) REFERENCES criteres_labellisation(id) ON DELETE CASCADE,\n  FOREIGN KEY (valide_par) REFERENCES users(id) ON DELETE SET NULL,\n  \n  UNIQUE(diagnostiqueur_id, critere_id)\n)"
      },
      {
        "sql": "CREATE TABLE el_audit_zones (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  el_audit_id INTEGER NOT NULL,\n  audit_token TEXT NOT NULL,\n  zone_id INTEGER NOT NULL,\n  zone_name TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (el_audit_id) REFERENCES el_audits(id) ON DELETE CASCADE,\n  FOREIGN KEY (audit_token) REFERENCES el_audits(audit_token) ON DELETE CASCADE,\n  FOREIGN KEY (zone_id) REFERENCES pv_zones(id) ON DELETE CASCADE,\n  UNIQUE(el_audit_id, zone_id)\n)"
      },
      {
        "sql": "CREATE TABLE el_audits (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER,\n  audit_token TEXT UNIQUE NOT NULL,\n  project_name TEXT NOT NULL,\n  client_name TEXT NOT NULL,\n  location TEXT,\n  string_count INTEGER NOT NULL,\n  modules_per_string INTEGER NOT NULL,\n  total_modules INTEGER NOT NULL,\n  configuration_json TEXT,\n  plan_file_url TEXT,\n  status TEXT DEFAULT 'created',\n  completion_rate REAL DEFAULT 0,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, client_id INTEGER REFERENCES crm_clients(id), audit_id INTEGER \n  REFERENCES audits(id) ON DELETE CASCADE,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE \"el_collaborative_sessions\" (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  audit_token TEXT NOT NULL,\n  technician_id INTEGER NOT NULL,\n  last_activity DATETIME DEFAULT CURRENT_TIMESTAMP,\n  is_active BOOLEAN DEFAULT 1,\n  cursor_position TEXT,\n  \n  \n  FOREIGN KEY (audit_token) REFERENCES el_audits(audit_token) ON DELETE CASCADE,\n  FOREIGN KEY (technician_id) REFERENCES auth_users(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE el_measurements (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER NOT NULL,\n  module_id INTEGER NOT NULL,\n  defect_type TEXT, \n  severity_level TEXT, \n  image_path TEXT,\n  current_injection REAL, \n  exposure_time REAL, \n  camera_settings TEXT, \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id),\n  FOREIGN KEY (module_id) REFERENCES modules(id)\n)"
      },
      {
        "sql": "CREATE TABLE \"el_modules\" (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  el_audit_id INTEGER NOT NULL,\n  audit_token TEXT NOT NULL,\n  module_identifier TEXT NOT NULL,\n  string_number INTEGER NOT NULL,\n  position_in_string INTEGER NOT NULL,\n  defect_type TEXT DEFAULT 'pending',\n  severity_level INTEGER DEFAULT 0,\n  comment TEXT,\n  technician_id INTEGER,\n  physical_row INTEGER,\n  physical_col INTEGER,\n  image_url TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  \n  FOREIGN KEY (el_audit_id) REFERENCES el_audits(id) ON DELETE CASCADE,\n  FOREIGN KEY (audit_token) REFERENCES el_audits(audit_token) ON DELETE CASCADE,\n  FOREIGN KEY (technician_id) REFERENCES auth_users(id) ON DELETE SET NULL,\n  UNIQUE(el_audit_id, module_identifier)\n)"
      },
      {
        "sql": "CREATE TABLE el_photos (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  el_module_id INTEGER NOT NULL,\n  audit_token TEXT NOT NULL,\n  module_identifier TEXT NOT NULL,\n  \n  \n  r2_key TEXT NOT NULL UNIQUE,\n  r2_url TEXT NOT NULL,\n  \n  \n  photo_type TEXT NOT NULL DEFAULT 'defect', \n  defect_category TEXT, \n  severity_level INTEGER DEFAULT 0, \n  \n  \n  description TEXT,\n  technician_notes TEXT,\n  capture_date DATETIME,\n  file_size INTEGER,\n  mime_type TEXT,\n  \n  \n  gps_latitude REAL,\n  gps_longitude REAL,\n  string_number INTEGER,\n  position_in_string INTEGER,\n  \n  \n  uploaded_by INTEGER, \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (el_module_id) REFERENCES el_modules(id) ON DELETE CASCADE,\n  FOREIGN KEY (audit_token) REFERENCES el_audits(audit_token) ON DELETE CASCADE,\n  FOREIGN KEY (uploaded_by) REFERENCES auth_users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE intervention_plants (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER NOT NULL,\n  plant_id INTEGER NOT NULL,\n  is_primary BOOLEAN DEFAULT 1,  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE CASCADE,\n  FOREIGN KEY (plant_id) REFERENCES pv_plants(id) ON DELETE CASCADE,\n  UNIQUE(intervention_id, plant_id)\n)"
      },
      {
        "sql": "CREATE TABLE \"interventions\" (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id INTEGER NOT NULL,\n  technician_id INTEGER,  \n  intervention_type TEXT NOT NULL,\n  intervention_date DATE NOT NULL,\n  duration_hours REAL,\n  status TEXT DEFAULT 'scheduled',\n  weather_conditions TEXT,\n  temperature_ambient REAL,\n  irradiance REAL,\n  notes TEXT,\n  report_url TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,\n  FOREIGN KEY (technician_id) REFERENCES auth_users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE isolation_measurements_history (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  test_id INTEGER NOT NULL,\n  test_token TEXT NOT NULL,\n  \n  \n  measurement_type TEXT NOT NULL, \n  measurement_value REAL NOT NULL, \n  is_conform BOOLEAN NOT NULL,\n  \n  \n  measured_at DATETIME NOT NULL,\n  \n  FOREIGN KEY (test_id) REFERENCES isolation_tests(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE isolation_tests (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  test_token TEXT UNIQUE NOT NULL,\n  \n  \n  plant_id INTEGER,\n  zone_id INTEGER,\n  audit_el_token TEXT,\n  \n  \n  test_date DATE NOT NULL,\n  test_type TEXT NOT NULL, \n  operator_name TEXT,\n  equipment_used TEXT, \n  \n  \n  dc_positive_to_earth REAL, \n  dc_negative_to_earth REAL, \n  dc_positive_to_negative REAL, \n  ac_to_earth REAL, \n  \n  \n  temperature_celsius REAL, \n  humidity_percent REAL, \n  weather_conditions TEXT, \n  \n  \n  is_conform BOOLEAN NOT NULL DEFAULT 0, \n  threshold_mohm REAL NOT NULL DEFAULT 1.0, \n  \n  \n  notes TEXT,\n  non_conformity_details TEXT, \n  corrective_actions TEXT, \n  \n  \n  imported_from_file TEXT, \n  raw_data_json TEXT, \n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n, audit_token TEXT, audit_id INTEGER \n  REFERENCES audits(id) ON DELETE CASCADE)"
      },
      {
        "sql": "CREATE TABLE iv_curves (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  el_audit_id INTEGER,\n  audit_token TEXT,\n  string_number INTEGER NOT NULL,\n  curve_type TEXT NOT NULL DEFAULT 'dark',\n  measurement_date DATETIME DEFAULT CURRENT_TIMESTAMP,\n  technician_id INTEGER,\n  device_name TEXT,\n  serial_number TEXT,\n  fill_factor REAL,\n  rds REAL,\n  uf_diodes INTEGER,\n  ur REAL,\n  isc REAL,\n  voc REAL,\n  pmax REAL,\n  vmpp REAL,\n  impp REAL,\n  rs REAL,\n  rsh REAL,\n  status TEXT DEFAULT 'pending',\n  anomaly_detected BOOLEAN DEFAULT 0,\n  anomaly_type TEXT,\n  source_filename TEXT,\n  source_file_url TEXT,\n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE \"iv_measurements\" (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    intervention_id INTEGER,  \n    string_number INTEGER,\n    module_number INTEGER,\n    measurement_type TEXT NOT NULL CHECK (measurement_type IN ('reference', 'dark')),\n    isc REAL,\n    voc REAL,\n    pmax REAL,\n    impp REAL,\n    vmpp REAL,\n    fill_factor REAL,\n    irradiance REAL,\n    temperature_module REAL,\n    temperature_ambient REAL,\n    iv_curve_data TEXT,\n    pmax_stc_corrected REAL,\n    deviation_from_datasheet REAL,\n    rs REAL,\n    rsh REAL,\n    notes TEXT,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    module_identifier TEXT,\n    audit_token TEXT,\n    audit_id INTEGER,\n    FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE SET NULL,\n    FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE labels_centrales (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id INTEGER NOT NULL,\n  \n  \n  numero_label TEXT NOT NULL UNIQUE,\n  \n  \n  \n  niveau TEXT NOT NULL CHECK(niveau IN ('bronze', 'argent', 'or', 'platine')),\n  \n  \n  \n  \n  \n  \n  taux_conformite REAL NOT NULL,\n  nombre_defauts_critiques INTEGER DEFAULT 0,\n  nombre_defauts_majeurs INTEGER DEFAULT 0,\n  nombre_defauts_mineurs INTEGER DEFAULT 0,\n  score_global REAL NOT NULL,\n  \n  \n  audit_conformite_id INTEGER,\n  audit_toiture_id INTEGER,\n  audit_el_id INTEGER,\n  audit_iv_id INTEGER,\n  audit_thermique_id INTEGER,\n  nombre_audits_realises INTEGER DEFAULT 0,\n  \n  \n  puissance_installee_kwc REAL,\n  production_estimee_kwh_an REAL,\n  performance_ratio REAL,\n  \n  \n  date_delivrance DATE NOT NULL,\n  date_expiration DATE NOT NULL,\n  duree_validite_annees INTEGER DEFAULT 2,\n  \n  \n  statut TEXT DEFAULT 'actif' CHECK(statut IN ('actif', 'suspendu', 'expire', 'revoque', 'en_renouvellement')),\n  raison_suspension TEXT,\n  date_suspension DATETIME,\n  \n  \n  public INTEGER DEFAULT 1,\n  qr_code_url TEXT,\n  url_verification TEXT,\n  \n  \n  delivre_par TEXT,\n  diagnostiqueur_principal_id INTEGER,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,\n  FOREIGN KEY (audit_conformite_id) REFERENCES audits(id) ON DELETE SET NULL,\n  FOREIGN KEY (diagnostiqueur_principal_id) REFERENCES diagnostiqueurs(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE labels_diagnostiqueurs (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  diagnostiqueur_id INTEGER NOT NULL,\n  \n  \n  numero_label TEXT NOT NULL UNIQUE,\n  \n  \n  \n  niveau TEXT NOT NULL CHECK(niveau IN ('junior', 'confirme', 'expert', 'formateur')),\n  \n  \n  \n  \n  \n  \n  specialites_certifiees TEXT NOT NULL,\n  \n  \n  \n  afpa_formation_completee INTEGER DEFAULT 0,\n  afpa_date_formation DATE,\n  afpa_formateur TEXT,\n  afpa_centre TEXT,\n  afpa_duree_heures INTEGER,\n  afpa_certificat_numero TEXT,\n  \n  \n  evaluation_theorique_score REAL,\n  evaluation_pratique_score REAL,\n  evaluation_terrain_score REAL,\n  note_evaluation_globale REAL,\n  \n  \n  date_delivrance DATE NOT NULL,\n  date_expiration DATE NOT NULL,\n  duree_validite_annees INTEGER DEFAULT 2,\n  \n  \n  statut TEXT DEFAULT 'actif' CHECK(statut IN ('actif', 'suspendu', 'expire', 'revoque')),\n  raison_suspension TEXT,\n  date_suspension DATETIME,\n  \n  \n  delivre_par TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (diagnostiqueur_id) REFERENCES diagnostiqueurs(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE labels_formations_continues (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  label_diagnostiqueur_id INTEGER NOT NULL,\n  \n  \n  titre_formation TEXT NOT NULL,\n  organisme TEXT,\n  formateur TEXT,\n  duree_heures INTEGER,\n  \n  \n  thematiques TEXT,\n  \n  \n  \n  date_formation DATE NOT NULL,\n  certificat_obtenu INTEGER DEFAULT 0,\n  note_obtenue REAL,\n  \n  \n  credits_formation INTEGER DEFAULT 0,\n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (label_diagnostiqueur_id) REFERENCES labels_diagnostiqueurs(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE labels_historique (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  type_label TEXT NOT NULL CHECK(type_label IN ('diagnostiqueur', 'centrale')),\n  label_id INTEGER NOT NULL,\n  \n  \n  action TEXT NOT NULL CHECK(action IN ('delivrance', 'renouvellement', 'suspension', 'revocation', 'reactivation')),\n  \n  \n  ancien_statut TEXT,\n  nouveau_statut TEXT,\n  ancienne_expiration DATE,\n  nouvelle_expiration DATE,\n  ancien_niveau TEXT,\n  nouveau_niveau TEXT,\n  \n  \n  raison TEXT NOT NULL,\n  commentaire TEXT,\n  \n  \n  effectue_par TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE labels_reclamations (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  type_label TEXT NOT NULL CHECK(type_label IN ('diagnostiqueur', 'centrale')),\n  label_id INTEGER NOT NULL,\n  \n  \n  reclamant_nom TEXT NOT NULL,\n  reclamant_email TEXT,\n  reclamant_telephone TEXT,\n  reclamant_relation TEXT,\n  \n  \n  \n  objet TEXT NOT NULL,\n  description TEXT NOT NULL,\n  gravite TEXT NOT NULL CHECK(gravite IN ('mineure', 'moderee', 'grave', 'critique')),\n  \n  \n  pieces_jointes TEXT,\n  \n  \n  \n  statut TEXT DEFAULT 'en_attente' CHECK(statut IN ('en_attente', 'en_cours', 'resolue', 'rejetee', 'escaladee')),\n  date_resolution DATETIME,\n  resolution_description TEXT,\n  mesures_correctives TEXT,\n  \n  \n  impact_label TEXT,\n  \n  \n  \n  assignee TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE missions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  project_id INTEGER NOT NULL,\n  intervention_id INTEGER, \n  \n  \n  titre TEXT NOT NULL,\n  description TEXT,\n  type_audit TEXT NOT NULL, \n  priorite TEXT DEFAULT 'normale' CHECK(priorite IN ('basse', 'normale', 'haute', 'urgente')),\n  \n  \n  site_address TEXT NOT NULL,\n  code_postal TEXT NOT NULL,\n  ville TEXT,\n  gps_latitude REAL,\n  gps_longitude REAL,\n  \n  \n  date_souhaitee DATE,\n  date_limite DATE,\n  duree_estimee_heures REAL DEFAULT 4,\n  \n  \n  competences_requises TEXT, \n  certification_minimale TEXT, \n  \n  \n  statut TEXT DEFAULT 'en_attente' CHECK(statut IN ('en_attente', 'proposee', 'affectee', 'acceptee', 'en_cours', 'terminee', 'validee', 'annulee')),\n  diagnostiqueur_affecte_id INTEGER, \n  date_affectation DATETIME,\n  date_acceptation DATETIME,\n  date_debut DATETIME,\n  date_fin DATETIME,\n  \n  \n  budget_prevu REAL,\n  tarif_horaire REAL DEFAULT 85,\n  frais_deplacement REAL DEFAULT 150,\n  \n  \n  notes_internes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  created_by INTEGER,\n  \n  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE SET NULL,\n  FOREIGN KEY (diagnostiqueur_affecte_id) REFERENCES diagnostiqueurs(id) ON DELETE SET NULL,\n  FOREIGN KEY (created_by) REFERENCES auth_users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE missions_historique (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  mission_id INTEGER NOT NULL,\n  statut_precedent TEXT,\n  statut_nouveau TEXT NOT NULL,\n  \n  commentaire TEXT,\n  modified_by INTEGER,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE CASCADE,\n  FOREIGN KEY (modified_by) REFERENCES auth_users(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE missions_propositions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  mission_id INTEGER NOT NULL,\n  diagnostiqueur_id INTEGER NOT NULL,\n  \n  \n  score_matching REAL DEFAULT 0, \n  distance_km REAL,\n  disponibilite_confirmee BOOLEAN DEFAULT 0,\n  \n  \n  statut TEXT DEFAULT 'proposee' CHECK(statut IN ('proposee', 'vue', 'acceptee', 'refusee', 'expiree')),\n  date_proposition DATETIME DEFAULT CURRENT_TIMESTAMP,\n  date_vue DATETIME,\n  date_reponse DATETIME,\n  motif_refus TEXT,\n  \n  \n  notification_envoyee BOOLEAN DEFAULT 0,\n  date_notification DATETIME,\n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE CASCADE,\n  FOREIGN KEY (diagnostiqueur_id) REFERENCES diagnostiqueurs(id) ON DELETE CASCADE,\n  UNIQUE(mission_id, diagnostiqueur_id)\n)"
      },
      {
        "sql": "CREATE TABLE module_configuration_sync (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  config_id INTEGER NOT NULL,\n  audit_token TEXT NOT NULL,\n  \n  module_type TEXT NOT NULL,\n  module_table TEXT NOT NULL,\n  \n  sync_status TEXT DEFAULT 'pending',\n  last_sync_at DATETIME,\n  sync_error TEXT,\n  \n  config_snapshot JSON,\n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (config_id) REFERENCES shared_configurations(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE module_positions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  project_id TEXT NOT NULL,\n  module_identifier TEXT NOT NULL,  \n  x_position REAL NOT NULL,  \n  y_position REAL NOT NULL,  \n  rotation REAL DEFAULT 0,   \n  width REAL DEFAULT 100,    \n  height REAL DEFAULT 40,    \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (project_id) REFERENCES calepinage_layouts(project_id),\n  UNIQUE(project_id, module_identifier)\n)"
      },
      {
        "sql": "CREATE TABLE photos (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  audit_token TEXT NOT NULL,\n  module_type TEXT NOT NULL DEFAULT 'GENERAL', \n  photo_data TEXT NOT NULL, \n  photo_format TEXT NOT NULL, \n  photo_size INTEGER NOT NULL, \n  description TEXT,\n  string_number INTEGER,\n  module_number INTEGER,\n  latitude REAL,\n  longitude REAL,\n  gps_accuracy REAL, \n  captured_at DATETIME, \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (audit_token) REFERENCES audits(audit_token) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE post_incident_expertise (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER NOT NULL,\n  incident_date DATE NOT NULL,\n  incident_type TEXT NOT NULL,\n  root_cause TEXT,\n  contributing_factors TEXT,\n  affected_modules_count INTEGER,\n  affected_strings_count INTEGER,\n  estimated_power_loss_kw REAL,\n  estimated_production_loss_kwh_year REAL,\n  estimated_financial_loss_eur REAL,\n  incident_photos_urls TEXT,\n  insurance_report_url TEXT,\n  expert_report_url TEXT,\n  safety_hazard BOOLEAN DEFAULT 0,\n  immediate_actions_required TEXT,\n  repair_recommendations TEXT,\n  prevention_recommendations TEXT,\n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE \"projects\" (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  client_id INTEGER NOT NULL,\n  name TEXT NOT NULL,\n  site_address TEXT NOT NULL,\n  installation_power REAL,\n  inverter_model TEXT,\n  module_model TEXT,\n  installation_date DATE,\n  commissioning_date DATE,\n  string_count INTEGER,\n  modules_per_string INTEGER,\n  total_modules INTEGER,\n  latitude REAL,\n  longitude REAL,\n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, inverter_count INTEGER DEFAULT 0, inverter_brand TEXT, junction_box_count INTEGER DEFAULT 0, strings_configuration TEXT, technical_notes TEXT, audit_types TEXT DEFAULT '[\"CONFORMITE\"]', is_girasole INTEGER DEFAULT 0, id_referent TEXT,\n  \n  \n  FOREIGN KEY (client_id) REFERENCES crm_clients(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE pv_cartography_audit_links (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  pv_zone_id INTEGER NOT NULL,\n  pv_plant_id INTEGER NOT NULL,\n  \n  \n  el_audit_id INTEGER NOT NULL,\n  el_audit_token TEXT NOT NULL,\n  \n  \n  link_type TEXT DEFAULT 'manual', \n  sync_direction TEXT DEFAULT 'el_to_pv', \n  sync_status TEXT DEFAULT 'linked', \n  last_sync_at DATETIME,\n  sync_error_message TEXT,\n  \n  \n  module_mapping TEXT, \n  \n  \n  total_modules_synced INTEGER DEFAULT 0,\n  modules_with_defects INTEGER DEFAULT 0,\n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n  \n  \n  \n  \n  \n  \n  \n  \n  \n)"
      },
      {
        "sql": "CREATE TABLE pv_inverters (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    zone_id INTEGER NOT NULL,\n    inverter_name TEXT NOT NULL,              -- \"Onduleur 1\", \"Onduleur 2\"\n    inverter_model TEXT,                      -- \"Huawei SUN2000-100KTL\", \"Fronius Symo\"\n    inverter_brand TEXT,                      -- \"Huawei\", \"Fronius\", \"SMA\"\n    rated_power_kw REAL NOT NULL,             -- 100.0 kW\n    mppt_count INTEGER DEFAULT 4,             -- Nombre de trackers MPPT\n    efficiency_percent REAL DEFAULT 98.0,     -- Rendement onduleur (%)\n    status TEXT DEFAULT 'active',             -- 'active', 'maintenance', 'offline'\n    installation_date DATE,                   -- Date installation\n    serial_number TEXT,                       -- Numéro de série\n    notes TEXT,                               -- Notes techniques\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (zone_id) REFERENCES pv_zones(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE pv_junction_boxes (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    zone_id INTEGER NOT NULL,\n    box_name TEXT NOT NULL,                   -- \"BJ1\", \"BJ-Nord\", \"Coffret A\"\n    box_type TEXT DEFAULT 'standard',         -- 'standard', 'dc', 'ac'\n    inverter_id INTEGER,                      -- Onduleur connecté (optionnel)\n    location_description TEXT,                -- \"Coin Nord-Est toiture\"\n    latitude REAL,                            -- Position GPS\n    longitude REAL,\n    installation_date DATE,\n    notes TEXT,\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (zone_id) REFERENCES pv_zones(id) ON DELETE CASCADE,\n    FOREIGN KEY (inverter_id) REFERENCES pv_inverters(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE pv_module_defects (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  module_id INTEGER NOT NULL,\n  \n  \n  module_status TEXT NOT NULL DEFAULT 'pending' CHECK(module_status IN (\n    'ok',              \n    'inequality',      \n    'microcracks',     \n    'dead',            \n    'string_open',     \n    'not_connected',   \n    'pending'          \n  )),\n  \n  \n  comment TEXT,\n  \n  \n  photo_url TEXT,\n  \n  \n  detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  detected_by TEXT, \n  \n  FOREIGN KEY (module_id) REFERENCES pv_modules(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE pv_modules (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  zone_id INTEGER NOT NULL,\n  \n  \n  module_identifier TEXT NOT NULL,\n  string_number INTEGER NOT NULL,\n  position_in_string INTEGER NOT NULL,\n  \n  \n  pos_x_meters REAL NOT NULL,\n  pos_y_meters REAL NOT NULL,\n  \n  \n  width_meters REAL DEFAULT 1.7,\n  height_meters REAL DEFAULT 1.0,\n  rotation INTEGER DEFAULT 0 CHECK(rotation IN (0, 90, 180, 270)),\n  \n  \n  latitude REAL,\n  longitude REAL,\n  \n  \n  power_wp INTEGER DEFAULT 450,\n  brand TEXT,\n  model TEXT,\n  serial_number TEXT,\n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, module_status TEXT DEFAULT 'pending' CHECK(module_status IN (\n  'ok', 'inequality', 'microcracks', 'dead', 'string_open', 'not_connected', 'pending'\n)), status_comment TEXT, el_photo_url TEXT, el_analysis_date DATETIME, el_defect_type TEXT, el_severity_level INTEGER DEFAULT 0, el_notes TEXT, el_technician_id INTEGER REFERENCES users(id), ir_photo_url TEXT, ir_hotspot_temp REAL, ir_analysis_date DATETIME, iv_curve_data TEXT, iv_isc REAL, iv_voc REAL, iv_pmax REAL, iv_fill_factor REAL, iv_analysis_date DATETIME, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, el_audit_id INTEGER, el_audit_token TEXT, el_module_id INTEGER,\n  \n  FOREIGN KEY (zone_id) REFERENCES pv_zones(id) ON DELETE CASCADE,\n  UNIQUE(zone_id, module_identifier)\n)"
      },
      {
        "sql": "CREATE TABLE pv_plants (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  plant_name TEXT NOT NULL,\n  plant_type TEXT DEFAULT 'rooftop' CHECK(plant_type IN ('rooftop', 'ground', 'carport')),\n  \n  \n  address TEXT,\n  city TEXT,\n  postal_code TEXT,\n  country TEXT DEFAULT 'France',\n  latitude REAL,\n  longitude REAL,\n  \n  \n  total_power_kwp REAL DEFAULT 0,\n  module_count INTEGER DEFAULT 0,\n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE pv_string_assignments (\n    id INTEGER PRIMARY KEY AUTOINCREMENT,\n    inverter_id INTEGER NOT NULL,\n    string_number INTEGER NOT NULL,           -- Numéro du string (1-N)\n    mppt_input INTEGER,                       -- Entrée MPPT (1-4, optionnel)\n    string_voltage_v REAL,                    -- Tension string (V)\n    string_current_a REAL,                    -- Courant string (A)\n    notes TEXT,                               -- Notes spécifiques\n    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n    FOREIGN KEY (inverter_id) REFERENCES pv_inverters(id) ON DELETE CASCADE,\n    -- Contrainte: Un string ne peut être attribué qu'à un seul onduleur\n    UNIQUE(inverter_id, string_number)\n)"
      },
      {
        "sql": "CREATE TABLE pv_structures (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  zone_id INTEGER NOT NULL,\n  \n  \n  structure_type TEXT NOT NULL CHECK(structure_type IN ('building', 'carport', 'ground', 'technical', 'other')),\n  structure_name TEXT NOT NULL,\n  structure_order INTEGER DEFAULT 1,\n  \n  \n  geometry TEXT NOT NULL, \n  area_sqm REAL DEFAULT 0,\n  \n  \n  fill_color TEXT DEFAULT '#e5e7eb',\n  stroke_color TEXT DEFAULT '#9ca3af',\n  opacity REAL DEFAULT 0.3,\n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (zone_id) REFERENCES pv_zones(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE pv_zones (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  plant_id INTEGER NOT NULL,\n  \n  \n  zone_name TEXT NOT NULL,\n  zone_type TEXT DEFAULT 'roof' CHECK(zone_type IN ('roof', 'ground', 'carport')),\n  zone_order INTEGER DEFAULT 1,\n  \n  \n  azimuth INTEGER DEFAULT 180 CHECK(azimuth >= 0 AND azimuth <= 360),\n  tilt INTEGER DEFAULT 30 CHECK(tilt >= 0 AND tilt <= 90),\n  \n  \n  outline_coordinates TEXT, \n  area_sqm REAL DEFAULT 0,\n  \n  \n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, background_image_url TEXT, background_image_type TEXT DEFAULT 'upload' CHECK(background_image_type IN ('upload', 'google_maps', 'none')), width_meters REAL DEFAULT 50.0, height_meters REAL DEFAULT 30.0, grid_config TEXT, inverter_count INTEGER DEFAULT 0, junction_box_count INTEGER DEFAULT 0, string_count INTEGER DEFAULT 0, modules_per_string INTEGER DEFAULT 0, roof_polygon TEXT, roof_area_sqm REAL, strings_config TEXT, rectangles_config TEXT DEFAULT NULL, audit_token TEXT, audit_id INTEGER, sync_status TEXT DEFAULT 'manual' CHECK(sync_status IN ('manual', 'auto', 'synced', 'conflict')), last_sync_at DATETIME, sync_direction TEXT DEFAULT 'pv_to_audit' CHECK(sync_direction IN ('pv_to_audit', 'audit_to_pv', 'bidirectional')),\n  \n  FOREIGN KEY (plant_id) REFERENCES pv_plants(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE pvserv_measurements (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER,\n  audit_token TEXT,\n  string_number INTEGER,\n  module_number INTEGER,\n  ff REAL,\n  rds REAL,\n  uf REAL,\n  measurement_type TEXT,\n  iv_curve_data TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, module_identifier TEXT,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE report_templates (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  template_code TEXT UNIQUE NOT NULL,      \n  display_name TEXT NOT NULL,              \n  description TEXT,                        \n  modules_required TEXT NOT NULL,          \n  modules_optional TEXT,                   \n  conformity_weights TEXT NOT NULL,        \n  report_sections TEXT NOT NULL,           \n  is_active BOOLEAN DEFAULT 1,\n  icon TEXT,                               \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE reports (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER NOT NULL,\n  report_type TEXT NOT NULL, \n  report_title TEXT NOT NULL,\n  executive_summary TEXT, \n  technical_findings TEXT, \n  recommendations TEXT, \n  performance_impact TEXT, \n  report_file_path TEXT, \n  generation_date DATETIME DEFAULT CURRENT_TIMESTAMP,\n  delivery_date DATETIME,\n  client_validation BOOLEAN DEFAULT FALSE,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id)\n)"
      },
      {
        "sql": "CREATE TABLE sessions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  user_id INTEGER NOT NULL,\n  session_token TEXT UNIQUE NOT NULL,\n  expires_at DATETIME NOT NULL,\n  ip_address TEXT,\n  user_agent TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES auth_users(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE shared_configurations (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  audit_id INTEGER,\n  audit_token TEXT UNIQUE NOT NULL,\n  \n  \n  string_count INTEGER,\n  modules_per_string INTEGER,\n  total_modules INTEGER NOT NULL,\n  \n  \n  advanced_config JSON,\n  is_advanced_mode BOOLEAN DEFAULT 0,\n  \n  \n  module_model TEXT,\n  module_power_wp INTEGER,\n  total_power_kwc REAL,\n  \n  \n  inverter_model TEXT,\n  inverter_count INTEGER DEFAULT 1,\n  installation_type TEXT,\n  orientation TEXT,\n  tilt_angle INTEGER,\n  \n  \n  validation_status TEXT DEFAULT 'draft',\n  validated_by TEXT,\n  validated_at DATETIME,\n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  created_by TEXT,\n  \n  FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE sqlite_sequence(name,seq)"
      },
      {
        "sql": "CREATE TABLE subcontractor_availability (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  subcontractor_id INTEGER NOT NULL,\n  \n  \n  date_start DATE NOT NULL,\n  date_end DATE NOT NULL,\n  \n  \n  availability_type TEXT DEFAULT 'available', \n  \n  \n  notes TEXT,\n  recurring BOOLEAN DEFAULT 0, \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (subcontractor_id) REFERENCES subcontractors(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE subcontractor_missions (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  subcontractor_id INTEGER NOT NULL,\n  intervention_id INTEGER NOT NULL,\n  \n  \n  mission_date DATE NOT NULL,\n  mission_type TEXT NOT NULL, \n  duration_hours REAL,\n  \n  \n  cost_amount REAL, \n  travel_distance_km REAL,\n  travel_cost REAL,\n  total_cost REAL,\n  \n  \n  report_delivered_at DATETIME,\n  report_delay_days INTEGER, \n  quality_rating INTEGER, \n  client_satisfaction INTEGER, \n  \n  \n  status TEXT DEFAULT 'planned', \n  \n  \n  internal_notes TEXT,\n  issues_encountered TEXT,\n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (subcontractor_id) REFERENCES subcontractors(id) ON DELETE CASCADE,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE subcontractors (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  company_name TEXT NOT NULL,\n  siret TEXT,\n  contact_name TEXT NOT NULL,\n  contact_email TEXT NOT NULL,\n  contact_phone TEXT,\n  address TEXT,\n  postal_code TEXT,\n  city TEXT,\n  country TEXT DEFAULT 'France',\n  \n  \n  specialties TEXT NOT NULL, \n  certifications TEXT, \n  equipment TEXT, \n  \n  \n  hourly_rate REAL, \n  daily_rate REAL, \n  travel_cost_per_km REAL DEFAULT 0.50, \n  \n  \n  max_concurrent_missions INTEGER DEFAULT 1, \n  availability_zone TEXT, \n  languages TEXT, \n  \n  \n  rating REAL DEFAULT 0.0, \n  total_missions INTEGER DEFAULT 0, \n  success_rate REAL DEFAULT 100.0, \n  average_report_delay REAL DEFAULT 5.0, \n  \n  \n  status TEXT DEFAULT 'active', \n  partnership_since DATE DEFAULT CURRENT_DATE,\n  last_mission_date DATE,\n  \n  \n  contract_type TEXT DEFAULT 'freelance', \n  contract_start_date DATE,\n  contract_end_date DATE,\n  insurance_valid_until DATE,\n  \n  \n  notes TEXT,\n  internal_comments TEXT, \n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n)"
      },
      {
        "sql": "CREATE TABLE thermal_measurements (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER NOT NULL,\n  measurement_method TEXT NOT NULL,\n  temperature_max REAL,\n  temperature_min REAL,\n  temperature_avg REAL,\n  delta_t_max REAL,\n  string_number INTEGER,\n  module_number INTEGER,\n  gps_latitude REAL,\n  gps_longitude REAL,\n  thermal_image_url TEXT,\n  thermal_map_url TEXT,\n  visible_image_url TEXT,\n  defect_type TEXT,\n  severity_level INTEGER,\n  notes TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (intervention_id) REFERENCES interventions(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE unified_reports (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  \n  \n  report_token TEXT UNIQUE NOT NULL,\n  \n  \n  plant_id INTEGER, \n  audit_el_token TEXT, \n  inspection_token TEXT, \n  \n  \n  report_title TEXT NOT NULL,\n  client_name TEXT NOT NULL,\n  audit_date DATE NOT NULL,\n  auditor_name TEXT,\n  \n  \n  overall_conformity_rate REAL NOT NULL, \n  critical_issues_count INTEGER DEFAULT 0,\n  major_issues_count INTEGER DEFAULT 0,\n  minor_issues_count INTEGER DEFAULT 0,\n  \n  \n  \n  modules_included TEXT NOT NULL,\n  \n  \n  html_content TEXT NOT NULL,\n  \n  \n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  generated_by TEXT, \n  report_version TEXT DEFAULT '1.0',\n  \n  \n  FOREIGN KEY (plant_id) REFERENCES pv_plants(id) ON DELETE SET NULL\n)"
      },
      {
        "sql": "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)"
      },
      {
        "sql": "CREATE TABLE visual_defects (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  inspection_id INTEGER NOT NULL,\n  inspection_token TEXT NOT NULL,\n  item_id INTEGER,\n  \n  \n  defect_location TEXT NOT NULL,\n  module_identifier TEXT,\n  string_number INTEGER,\n  equipment_type TEXT NOT NULL,\n  \n  \n  defect_type TEXT NOT NULL,\n  defect_category TEXT NOT NULL,\n  severity TEXT NOT NULL,\n  urgency TEXT DEFAULT 'medium',\n  \n  \n  description TEXT NOT NULL,\n  potential_impact TEXT,\n  recommended_action TEXT,\n  \n  \n  norm_reference TEXT,\n  norm_violation BOOLEAN DEFAULT 0,\n  \n  \n  image_url TEXT,\n  image_count INTEGER DEFAULT 0,\n  \n  \n  detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  detected_by TEXT,\n  resolved BOOLEAN DEFAULT 0,\n  resolved_at DATETIME,\n  \n  FOREIGN KEY (inspection_id) REFERENCES visual_inspections(id) ON DELETE CASCADE,\n  FOREIGN KEY (item_id) REFERENCES visual_inspection_items(id)\n)"
      },
      {
        "sql": "CREATE TABLE visual_inspection_items (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  inspection_id INTEGER NOT NULL,\n  inspection_token TEXT NOT NULL,\n  \n  \n  category TEXT NOT NULL,\n  subcategory TEXT,\n  item_code TEXT NOT NULL,\n  item_description TEXT NOT NULL,\n  \n  \n  status TEXT DEFAULT 'pending',\n  conformity TEXT DEFAULT 'pending',\n  severity TEXT DEFAULT 'info',\n  \n  \n  observation TEXT,\n  recommendation TEXT,\n  \n  \n  photo_url TEXT,\n  photo_count INTEGER DEFAULT 0,\n  \n  \n  checked_at DATETIME,\n  checked_by TEXT,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  \n  FOREIGN KEY (inspection_id) REFERENCES visual_inspections(id) ON DELETE CASCADE\n)"
      },
      {
        "sql": "CREATE TABLE visual_inspection_photos (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  inspection_id INTEGER NOT NULL,\n  inspection_token TEXT NOT NULL,\n  item_id INTEGER,\n  defect_id INTEGER,\n  \n  \n  photo_url TEXT NOT NULL,\n  photo_type TEXT NOT NULL,\n  caption TEXT,\n  \n  \n  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  uploaded_by TEXT,\n  file_size INTEGER,\n  \n  FOREIGN KEY (inspection_id) REFERENCES visual_inspections(id) ON DELETE CASCADE,\n  FOREIGN KEY (item_id) REFERENCES visual_inspection_items(id),\n  FOREIGN KEY (defect_id) REFERENCES visual_defects(id)\n)"
      },
      {
        "sql": "CREATE TABLE visual_inspections (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  intervention_id INTEGER,  \n  audit_token TEXT,\n  audit_id INTEGER,\n  inspection_type TEXT NOT NULL,\n  string_number INTEGER,\n  module_number INTEGER,\n  location_description TEXT,\n  defect_found BOOLEAN DEFAULT 0,\n  defect_type TEXT,\n  severity_level INTEGER,\n  photo_url TEXT,\n  gps_latitude REAL,\n  gps_longitude REAL,\n  corrective_action_required BOOLEAN DEFAULT 0,\n  corrective_action_description TEXT,\n  notes TEXT,\n  inspection_date DATE DEFAULT CURRENT_DATE,\n  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n  plant_id INTEGER, conformite TEXT CHECK(conformite IN ('conforme', 'non_conforme', 'so', NULL)), prescriptions_girasole TEXT, bonnes_pratiques TEXT, audit_category TEXT DEFAULT 'general', checklist_section TEXT, item_order INTEGER DEFAULT 0, checklist_type TEXT DEFAULT 'IEC_62446', project_id INTEGER,\n  \n  FOREIGN KEY (audit_token) REFERENCES audits(audit_token) ON DELETE CASCADE\n)"
      }
    ],
    "success": true,
    "meta": {
      "served_by": "v3-prod",
      "served_by_region": "WNAM",
      "served_by_primary": true,
      "timings": {
        "sql_duration_ms": 0.4221
      },
      "duration": 0.4221,
      "changes": 0,
      "last_row_id": 0,
      "changed_db": false,
      "size_after": 3944448,
      "rows_read": 408,
      "rows_written": 0,
      "total_attempts": 1
    }
  }
]
